### ISSUE TITLE
lack text information about NTU RGB+D

### ISSUE THREAD

**Issue by wanluzhu** [line/Human-Interaction-Generation#1]
Thank you for your great work.
I encountered a ‘ValueError’ when trying to load the dataset for my project. Here is the traceback of the error:
![image](https://github.com/line/Human-Interaction-Generation/assets/87316742/3eabe73c-8220-4c69-a5a4-f21d54d830b8)
It seems that the error is caused by missing text information for the dataset.
Could you please provide guidance on how to resolve this issue? Thank you!

**Comment by mikittt** [comment]
Thank you for your interest.
Could you tell me what kind of error would occur if you remove 'try&except' [here](https://github.com/line/Human-Interaction-Generation/blob/5b494e94275131805005a9b301d73c5c2844e6ab/codes/datasets/evaluator.py#L196)?

**Comment by shun-Maeda** [comment]
We have removed 'try&except' as you mentioned, and now the error occurred.
![Screenshot from 2024-05-26 03-38-40](https://github.com/line/Human-Interaction-Generation/assets/107637568/952bfc32-e904-43b4-ad20-994ef2a824ff)
It seems like the "S00...rgb.txt" do not exist (or not created).
Actually, the "texts" folder also does not exist.
It would be great if you could tell us the possible solution, thanks!

**Comment by mikittt** [comment]
Thank you for your comment. 
As you mentioned, I forgot to upload the text directory. 
You can download it from this [link](https://drive.google.com/file/d/1IWYAaP8zAUiRKuH1SumLzmesCOVRPgsX/view?usp=sharing). 
I apologize for the inconvenience.

**Comment by wanluzhu** [comment]
Thank you!
